name: 'Upload file'
description: 'Create an upload to a devicefarm project and upload a file'
inputs:
  project_arn:
    description: 'ARN of an existing device farm project'
    required: true
  type:
    description: 'Type of the file to upload'
    required: true
  name:
    description: 'Name of the file to upload'
    required: false
  file:
    description: 'Path of the file to upload'
    required: true
  cleanup:
    description: 'Remove uploads before exiting'
    required: true
    default: true
  remote_src:
    description: 'Source file is on a remote HTTP server'
    required: true
    default: false
outputs:
  data:
    description: 'JSON data returned from the API'
  arn:
    description: 'The ARN of the newly created upload'
  url:
    description: 'The URL of the newly created upload'
  status:
    description: 'The status of the newly created upload'
runs:
  using: 'node16'
  main: 'index.js'